import {
  Table,
  Column,
  Model,
  DataType,
  PrimaryKey,
  Default,
  HasMany,
  HasOne,
  CreatedAt,
  UpdatedAt,
} from 'sequelize-typescript';
import { TravellerEntity } from './traveller.entity';
import { PaymentEntity } from './payment.entity';
import { SupplierBookingEntity } from './supplier-booking.entity';

/**
 * Payment status — tracks whether the customer has paid.
 * Separate from booking status because payment and booking are separate concerns.
 */
export enum PaymentStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUNDED = 'REFUNDED',
}

/**
 * Booking status — tracks the overall booking lifecycle.
 *
 * State machine:
 * PENDING → PAYMENT_RECEIVED → SUPPLIER_BOOKING → CONFIRMED
 *                            → SUPPLIER_UNKNOWN (timeout)
 *                            → FAILED
 * CONFIRMED → CANCELLATION_REQUESTED → CANCELLED
 */
export enum BookingStatus {
  PENDING = 'PENDING',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  SUPPLIER_BOOKING = 'SUPPLIER_BOOKING',
  SUPPLIER_UNKNOWN = 'SUPPLIER_UNKNOWN', // Timeout — we don't know if supplier booked
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
  CANCELLATION_REQUESTED = 'CANCELLATION_REQUESTED',
  CANCELLED = 'CANCELLED',
}

/**
 * Booking entity — the central record.
 *
 * Why not one big "order" table?
 * Payment details, traveller details, and supplier details each have
 * their own concerns and may change independently.
 * Normalizing them into separate tables makes queries cleaner and
 * keeps each table focused on its own data.
 *
 * bookingRef (TXG-XXXXXX) is what we show to the customer.
 * id is the internal UUID primary key.
 */
@Table({ tableName: 'bookings', timestamps: true, underscored: true })
export class BookingEntity extends Model {
  @PrimaryKey
  @Default(DataType.UUIDV4)
  @Column(DataType.UUID)
  declare id: string;

  /** Customer-facing reference e.g. TXG-123456 */
  @Column({ type: DataType.STRING(20), allowNull: false, unique: true })
  declare bookingRef: string;

  /** The Tixxgo offer ID used to track which flight was booked */
  @Column({ type: DataType.STRING(36), allowNull: false })
  declare offerId: string;

  /** Which supplier (TBO, TripJack, etc.) */
  @Column({ type: DataType.STRING(50), allowNull: false })
  declare supplier: string;

  /** Supplier's internal result key (stored for reconciliation) */
  @Column({ type: DataType.STRING(100), allowNull: false })
  declare supplierResultKey: string;

  // Pricing snapshot at time of booking
  @Column({ type: DataType.DECIMAL(10, 2), allowNull: false })
  declare supplierBaseFare: number;

  @Column({ type: DataType.DECIMAL(10, 2), allowNull: false })
  declare supplierTaxes: number;

  @Column({ type: DataType.DECIMAL(10, 2), allowNull: false })
  declare serviceFee: number;

  @Column({ type: DataType.DECIMAL(10, 2), allowNull: false })
  declare discount: number;

  @Column({ type: DataType.DECIMAL(10, 2), allowNull: false })
  declare finalPrice: number;

  @Column({ type: DataType.STRING(3), allowNull: false, defaultValue: 'INR' })
  declare currency: string;

  // Flight snapshot
  @Column({ type: DataType.STRING(10), allowNull: false })
  declare flightNumber: string;

  @Column({ type: DataType.STRING(10), allowNull: false })
  declare origin: string;

  @Column({ type: DataType.STRING(10), allowNull: false })
  declare destination: string;

  @Column({ type: DataType.DATE, allowNull: false })
  declare departureTime: Date;

  @Column({ type: DataType.DATE, allowNull: false })
  declare arrivalTime: Date;

  @Column({
    type: DataType.ENUM(...Object.values(PaymentStatus)),
    allowNull: false,
    defaultValue: PaymentStatus.PENDING,
  })
  declare paymentStatus: PaymentStatus;

  @Column({
    type: DataType.ENUM(...Object.values(BookingStatus)),
    allowNull: false,
    defaultValue: BookingStatus.PENDING,
  })
  declare bookingStatus: BookingStatus;

  /**
   * Idempotency key — prevents duplicate bookings.
   * Generated by the client before payment. If the same key is sent twice,
   * we return the existing booking instead of creating a new one.
   */
  @Column({ type: DataType.STRING(100), allowNull: false, unique: true })
  declare idempotencyKey: string;

  @CreatedAt
  declare createdAt: Date;

  @UpdatedAt
  declare updatedAt: Date;

  // Relationships
  @HasMany(() => TravellerEntity)
  declare travellers: TravellerEntity[];

  @HasOne(() => PaymentEntity)
  declare payment: PaymentEntity;

  @HasOne(() => SupplierBookingEntity)
  declare supplierBooking: SupplierBookingEntity;
}
